#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.atmaterial >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.atmateriall=/luci-static/atmaterial
		set luci.main.mediaurlbase=/luci-static/atmaterial
		commit luci
	EOF
fi

exit 0
